import {
  Brand,
  Nav,
  Navbar,
  NavItem,
  NavLink,
} from "@/components/ui/NavComponents";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  const brand = { text: "Librazen", href: "/home" };
  let links = [
    { text: "Admin", href: "/admin", alignment: "left" },
    { text: "Catalogue", href: "/catalogue", alignment: "center" },
    { text: "Profile", href: "/profile", alignment: "right" },
    { text: "Cart", href: "/cart", alignment: "right" },
    { text: "Logout", href: "/", alignment: "right" },
  ];
  //TODO: Section to check user's admin auth...

  //Change links here
  if (!false) {
    links.splice(0, 1); //hard-coded for now...
  }

  const leftLinks = links.filter((link) => link.alignment === "left");
  const centerLinks = links.filter((link) => link.alignment === "center");
  const rightLinks = links.filter((link) => link.alignment === "right");

  return (
    <html lang="en">
      <body>
        <div className="h-full items-center justify-center bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-cyan-300 to-sky-500">
            <Navbar>
            <Brand href={brand.href}>{brand.text}</Brand>
            <Nav alignment="left">
                {leftLinks.map((link) => (
                <NavItem key={link.href}>
                    <NavLink href={link.href}>{link.text}</NavLink>
                </NavItem>
                ))}
            </Nav>
            <Nav alignment="center">
                {centerLinks.map((link) => (
                <NavItem key={link.href}>
                    <NavLink href={link.href}>{link.text}</NavLink>
                </NavItem>
                ))}
            </Nav>
            <Nav alignment="right">
                {rightLinks.map((link) => (
                <NavItem key={link.href}>
                    <NavLink href={link.href}>{link.text}</NavLink>
                </NavItem>
                ))}
            </Nav>
            </Navbar>
            {children}    
        </div>
      </body>
    </html>
  );
}
