import {
  Nav,
  Navbar,
} from "@/components/ui/NavComponents";
import { getInitialUserData } from "@/supabase/actions/supabase-actions";
import { cartList } from "@/utils/links";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function HomeTemplate({ children }) {
  const [{ customer_id, username, email, is_admin, profile_picture }] =
    await getInitialUserData();

  let links = [...cartList]

  const [brand] = links.filter((link) => link && link.text === "Librazen")
  const leftLinks = links.filter((link) => link && link.alignment === "left");
  const centerLinks = links.filter((link) => link &&link.alignment === "center");
  const rightLinks = links.filter((link) => link && link.alignment === "right");

  return (
    <>
      <Navbar>
        {brand.component}
        <Nav alignment="left">
          {leftLinks.map((link) => (
            link.component
          ))}
        </Nav>
        <Nav alignment="center">
          {centerLinks.map((link) => (
            link.component
          ))}
        </Nav>
        <Nav alignment="right">
          {rightLinks.map((link) => (
            link.component
          ))}
        </Nav>
      </Navbar>
      {children}
    </>
  );
}
